// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/lucasd-coder/classroom/internal/pkg/database"
	"github.com/lucasd-coder/classroom/internal/repository"
	"github.com/lucasd-coder/classroom/internal/service"
)

// Injectors from wire.go:

func InitializeCoursesRepository() *repository.CoursesRepository {
	db := database.GetDatabase()
	coursesRepository := repository.NewCoursesRepository(db)
	return coursesRepository
}

func InitializeEnrollemtsRepository() *repository.EnrollmentsRepository {
	db := database.GetDatabase()
	enrollmentsRepository := repository.NewEnrollmentsRepository(db)
	return enrollmentsRepository
}

func InitializeStudentsRepository() *repository.StudentsRepository {
	db := database.GetDatabase()
	studentsRepository := repository.NewStudentsRepository(db)
	return studentsRepository
}

func InitializeCoursesService() *service.CoursesService {
	coursesRepository := InitializeCoursesRepository()
	coursesService := service.NewCoursesService(coursesRepository)
	return coursesService
}

func InitializeEnrollemtsService() *service.EnrollmentsService {
	enrollmentsRepository := InitializeEnrollemtsRepository()
	enrollmentsService := service.NewEnrollmentsService(enrollmentsRepository)
	return enrollmentsService
}

func InitializeStudentsService() *service.StudentsService {
	studentsRepository := InitializeStudentsRepository()
	studentsService := service.NewStudentsService(studentsRepository)
	return studentsService
}
