// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/lucasd-coder/classroom/internal/pkg/database"
	"github.com/lucasd-coder/classroom/internal/repository"
	"github.com/lucasd-coder/classroom/internal/service"
)

// Injectors from wire.go:

func InitializeCoursesRepository() *repository.CoursesRepository {
	db := database.GetDatabase()
	coursesRepository := repository.NewCoursesRepository(db)
	return coursesRepository
}

func InitializeCoursesService() *service.CoursesService {
	coursesRepository := InitializeCoursesRepository()
	coursesService := service.NewCursesService(coursesRepository)
	return coursesService
}
